### This is going to be single dimension array

In [2]:
import  numpy as np
n1 = np.array([10,20,30,40])
print(n1)

[10 20 30 40]


### This is going to be two dimension array

In [1]:
import  numpy as np
n2 = np.array([[10,20,30,40],[50,60,70,80]])
print(n2)

[[10 20 30 40]
 [50 60 70 80]]


In [7]:
n1= np.zeros((1,2))
n1

array([[0., 0.]])

In [11]:
n3 = np.zeros((2,3))
type(n3)

numpy.ndarray

In [17]:
n4 = np.full((2,3),10)
n4

array([[10, 10, 10],
       [10, 10, 10]])

In [72]:
# this is used to view  the type of the nparray 
type(n4)

numpy.ndarray

In [73]:
#  This is used to make array with different steps count from a given range
n5 = np.arange(10,50,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [34]:
n6 = np.arange(50,500,10)
n6

array([ 50.,  60.,  70.,  80.,  90., 100., 110., 120., 130., 140., 150.,
       160., 170., 180., 190., 200., 210., 220., 230., 240., 250., 260.,
       270., 280., 290., 300., 310., 320., 330., 340., 350., 360., 370.,
       380., 390., 400., 410., 420., 430., 440., 450., 460., 470., 480.,
       490., 500.])

##### This is going to give us the output of randomfive numbers

In [46]:
n7 = np.random.randint(1,100,5)
n7

array([22, 18, 79, 89, 18])

In [47]:
n7.shape

(5,)

In [61]:
n8 = np.array([[1,2,3,5],[6,7,8,2]])
n8

array([[1, 2, 3, 5],
       [6, 7, 8, 2]])

In [63]:
n8.reshape(1,8)

array([[1, 2, 3, 5, 6, 7, 8, 2]])

In [65]:
n8.reshape(8,1)

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8],
       [2]])

In [70]:
# This is used to vertical stacking
np.vstack((n7,n7))

array([[22, 18, 79, 89, 18],
       [22, 18, 79, 89, 18]])

In [71]:
#  This is used for horizontal stacking
np.hstack((n8,n8))

array([[1, 2, 3, 5, 1, 2, 3, 5],
       [6, 7, 8, 2, 6, 7, 8, 2]])

In [82]:
#  This is going to give us the output of the intersecting point in array where the given two of the array array are going to intersect
n9 = np.array([10,20,30,40,50,60])
n10 = np.array([50,60,70,80,90])
np.intersect1d(n9,n10)
# or u can say the find the common elements

array([50, 60])

In [81]:
#  This is going to differentiate between the given arrays
np.setdiff1d(n10,n9)

array([70, 80, 90])

In [108]:
np.sum([n2,n2])

720

In [107]:
np.sum([n1])

40

In [104]:
x = n4.reshape(1,6)+n4.reshape(1,6)
y = n4.reshape(1,6)+n4.reshape(1,6)
x,y

(array([[20, 20, 20, 20, 20, 20]]), array([[20, 20, 20, 20, 20, 20]]))

In [105]:
np.sum([x,y])

240

In [116]:
np.sum([n9])

210

In [111]:
n10,n9

(array([50, 60, 70, 80, 90]), array([10, 20, 30, 40, 50, 60]))

In [119]:
(n9+1)%5

array([1, 1, 1, 1, 1, 1], dtype=int32)

In [120]:
n1

array([[10, 10],
       [10, 10]])

In [126]:
n1 = n1.reshape(1,4)
n1//10

array([[1, 1, 1, 1]], dtype=int32)

In [127]:
#  mean
np.mean(n1)

10.0

In [132]:
#  standard deviation
np.random.randint(1,50,10),
np.median(n1)
np.std(n1)

0.0

In [135]:
np.save('My_numpy.npy',n1)
n1

array([[10, 10, 10, 10]])

In [138]:
n2 = np.load('My_numpy.npy')
n2

array([[10, 10, 10, 10]])

In [143]:
x = np.zeros(9)
np.save('new.npy',x)

In [145]:
v = np.load('new.npy')
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])